name: SignTool detached digest generator
description: Generate a digest and partially signed artifact for further processing by remotesign workflow and codesign/apply-signed-digest action
author: tim-seves
inputs:
  path:
    description: path of the files to sign, with one path or glob per line.
    required: true
  algorithm:
    description: Digest hash algorithm
    default: "sha256"
    required: true
  url:
    description: Description URL to include in the signed file.
    default: "https://software.sil.org"
  public-cert:
    description: Secret containing the Base64 encoded public cert to sign against.
    required: true
outputs:
    job: 
      description: The job describing the file and parameters to be processed by the sign-digest workflow.
      value: ${{ steps.digest.outputs.job }}
runs:
  using: composite
  steps:
  - name: Generate digest and artifact
    id: digest
    env:
      signtool: C:/"Program Files (x86)"/"Windows Kits"/10/bin/10.0.17763.0/x86/signtool.exe
    shell: pwsh
    run: |
      $PublicCert = [System.Convert]::FromBase64String('${{ inputs.public-cert }}')
      Set-Content $ENV:TEMP\certificate -Value ($PublicCert) -AsByteStream
      $Targets = '${{ inputs.path }}'.Trim().Split([Environment]::NewLine, [StringSplitOptions]::RemoveEmptyEntries)
      $ResolvedTargets = Get-Item -Path $Targets

      ${{env.signtool}} sign /f $ENV:TEMP\certificate /dg . /fd ${{ inputs.algorithm }} /du ${{ inputs.url }} /v $ResolvedTargets

      $job = @{
        id='${{ hashFiles(inputs.path) }}'
        algorithm='${{ inputs.algorithm }}'
        targets=$Targets
      } | ConvertTo-Json -Compress
      Write-Output ('job=' + $job) >> $ENV:GITHUB_OUTPUT

  - uses: actions/upload-artifact@v4
    with:
      name: codesign-job-${{ fromJSON(steps.digest.outputs.job).id }}
      path: |
        ${{ inputs.path }}
        *.p7u
  - uses: actions/upload-artifact@v4
    with:
      name: codesign-digests-${{ fromJSON(steps.digest.outputs.job).id }}
      path: *.dig