name: Demonstrate use of fine grained actions with sign-digest.yml workflow
on:
  push:
    paths:
    - .github/workflows/sign-digest.yml
    - .github/workflows/actions-example.yml
    - apply-signed-digest/**
    - generate-digest/**
    - timestamp/**
    - verify-signature/**

jobs:
  build:
    runs-on: windows-latest
    outputs:
      job1: ${{ steps.generate.outputs.job }}
    steps:
    - uses: actions/checkout@v4

    # build your exe, dll or msi here
    # you can build multiple deliverables here and call generate-digest many times,
    # provided you store each invocation's artifact and digest pair separately.

    - name: Generate job from file and certificate.
      id: generate
      uses: sillsdev/codesign/generate-digest@fix/too-much-state
      with:
        path: |
          gdlpp.exe
          grcompiler.exe
          *.dll
        public-cert: ${{ secrets.CODESIGN_LSDEVSECTIGOEV }}

  sign:
    needs: build
    uses: sillsdev/codesign/.github/workflows/sign-digest.yml@fix/too-much-state
    with:
      job: ${{ needs.build.outputs.job1 }}
  
  attach:
    needs: sign
    runs-on: windows-latest
    steps:
    # you can apply multiple signature by calling apply-signed-digest many times,
    # provided you reference each invocation's artifact and digest pair separately.
    - name: Apply signatures to file in job
      uses: sillsdev/codesign/apply-signed-digest@fix/too-much-state
      with:
        job: ${{ needs.sign.outputs.signed-job }}

    # Same potential to timestamp, and/or verify mulitple signed deliverables.
    - name: Timestamp file in job
      uses:  sillsdev/codesign/timestamp@fix/too-much-state
      with:
        path: '*.exe'

    - name: Confirm signature
      uses: sillsdev/codesign/verify-signature@fix/too-much-state
      with:
        path:  '*.exe'