name: Demonstrate use of fine grained actions with sign-digest.yml workflow
on:
  push:
    paths:
    - .github/workflows/sign.yml
    - .github/workflows/actions-example.yml
    - apply-signed-digest/**
    - generate-digest/**
    - timestamp/**
    - verify-signature/**

jobs:
  build:
    runs-on: windows-latest
    outputs:
      digest: ${{ steps.generate.outputs.digest }}
      intermediates: ${{ steps.generate.outputs.artifact }}
    steps:
    - uses: actions/checkout@v4
    
    # build your exe, dll or msi here
    # you can build multiple deliverables here and call generate-digest many times,
    # provided you store each invocation's artifact and digest pair separately.

    - id: generate
      uses: sillsdev/codesign/generate-digest@v1
      with:
        path: grcompiler.exe
        public-cert: ${{ secrets.CODESIGN_LSDEVSECTIGOEV }}

  remotesign:
    needs: build
    uses: sillsdev/codesign/.github/workflows/sign-digest.yml@v1
    with:
      target: grcompiler.exe
      digest: ${{needs.build.outputs.digest}}
  
  attach:
    needs: [build, remotesign]
    runs-on: windows-latest
    steps:
    # you can apply multiple signature by calling apply-signed-digest many times,
    # provided you reference each invocation's artifact and digest pair separately.
    - uses: sillsdev/codesign/apply-signed-digest@v1
      with:
        artifact: ${{ needs.build.outputs.intermediates }}
        path: grcompiler.exe
        signed-digest: ${{ needs.remotesign.outputs.signed-digest }}

    # Same potential to timestamp, and/or verify mulitple signed deliverables.
    - id: timestamp
      uses:  sillsdev/codesign/timestamp@v1
      with:
        path: grcompiler.exe

    - name: Confirm signature
      uses: sillsdev/codesign/verify-signature@v1
      with:
        path: grcompiler.exe