name: Demonstrate simple sign.yml workflow.
on:
  push:
    paths:
    - .github/workflows/sign.yml
    - .github/workflows/sign-example.yml
    - verify-signature/**
    - trusted-signing-action/**

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: sillsdev/codesign/trusted-signing-action@feat/trusted-signing-service-action
      with:
        authentication: ${{ secrets.AZURE_TRUSTED_SIGNING_CREDENTIALS}}
        account: ${{ vars.TRUSTED_SIGNING_TEST_CERT }}
        files: |
          ${{ github.workspace }}\grcompiler.exe
          ${{ github.workspace }}\gdlpp.exe
        description: Graphite Description Language compiler
        description-url: https://graphite.sil.org

    - name: Confirm signature
      uses: sillsdev/codesign/verify-signature@feat/trusted-signing-service-action
      with:
        path: g*.exe
