name: Sign file
on:
  workflow_call:
    inputs:
      profile:
        default: "LsDevSectigoEV"
        type: string
      algorithm:
        default: "sha256"
        type: string
      url:
        default: "https://software.sil.org"
        type: string
      artifact:
        required: true
        type: string
    secrets:
      certificate:
        required: true
env:
  signtool: C:/"Program Files (x86)"/"Windows Kits"/10/bin/10.0.17763.0/x86/signtool.exe
  timestamp_url: http://timestamp.sectigo.com

jobs:
  digest:
    runs-on: windows-latest
    outputs:
      job: ${{ steps.generate.outputs.job }}
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact }}
        path: targets-${{ inputs.artifact }}

    - id: generate
      uses: sillsdev/codesign/generate-digest@v2.0.1
      with:
        path: targets-${{ inputs.artifact }}/*
        algorithm: ${{ inputs.algorithm }}
        url: ${{ inputs.url }}
        public-cert: ${{ secrets.certificate }}

  remotesign:
    needs: digest
    uses: sillsdev/codesign/.github/workflows/sign-digest.yml@v2.0.1
    with:
      job: ${{ needs.digest.outputs.job }}
   
  finalise:
    needs: remotesign
    runs-on: windows-latest
    steps:
    - uses: sillsdev/codesign/apply-signed-digest@v2.0.1
      with:
        path: targets-${{ inputs.artifact }}
        job: ${{ needs.remotesign.outputs.signed-job }}

    - id: timestamp
      uses:  sillsdev/codesign/timestamp@v2.0.1
      with:
        path: targets-${{ inputs.artifact }}/*
    
    - id: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.artifact}}
        path: targets-${{inputs.artifact}}
        if-no-files-found: error
        overwrite: true
