name: Sign digest
on:
  workflow_call:
    inputs:
      provider:
        default: "LsDevSectigoEV"
        type: string
      job:
        required: true
        type: string
    outputs:
      signed-job:
        description: "Signature for the supplied digest"
        value: ${{ toJSON(jobs.sign-digest.outputs) }}
env:
  job: ${{ fromJSON(inputs.job) }}
jobs:
  sign-digest:
    runs-on: [self-hosted, ltops-signing]
    outputs:
      digest: ${{ steps.sign.outputs }}
    steps:
    - id: sign
      run: |
        signed_digest=$(sign-digest ${{inputs.provider}} ${{env.job.algorithm}} '${{env.job.digest}}')
        echo "id=${{ env.job.id }}" >> "$GITHUB_OUTPUT"
        echo "algorithm=${{ env.job.algorithm }}" >> "$GITHUB_OUTPUT"
        echo "path=${{ env.job.path }}"
        echo "signed-digest=$signed_digest" >> "$GITHUB_OUTPUT"
