name: Demonstrate simple sign.yml workflow.
on:
  push:
    paths:
    - .github/workflows/sign.yml
    - .github/workflows/sign-digest.yml
    - .github/workflows/sign-example.yml
    - apply-signed-digest/**
    - generate-digest/**
    - timestamp/**
    - verify-signature/**

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Upload job to be signed
      uses: actions/upload-artifact@v4
      with:
        name: grcompiler
        path: g*.exe

  sign:
    needs: build
    uses: sillsdev/codesign/.github/workflows/sign.yml@fix/switch-to-new-gh-runner
    with:
      artifact: grcompiler
      description: Graphite
    secrets:
      certificate: ${{ secrets.CODESIGN_LSDEVSECTIGOEV }}

  test:
    runs-on: windows-latest
    needs: sign
    env:
      signtool: C:/"Program Files (x86)"/"Windows Kits"/10/bin/10.0.17763.0/x86/signtool.exe
    steps:
    - name: Download signed and timestamped job
      uses: actions/download-artifact@v4
      with:
        name: grcompiler

    - name: Confirm signature
      uses: sillsdev/codesign/verify-signature@v2
      with:
        path: g*.exe
