name: Sign file
on:
  workflow_call:
    inputs:
      profile:
        default: "LsDevSectigoEV"
        type: string
      hash:
        default: "sha256"
        type: string
      url:
        default: "https://software.sil.org"
        type: string
      target:
        required: true
        type: string
    secrets:
      certificate:
        required: true
env:
  signtool: C:/"Program Files (x86)"/"Windows Kits"/10/bin/10.0.17763.0/x86/signtool.exe
  timestamp_url: http://timestamp.sectigo.com

jobs:
  digest:
    runs-on: windows-latest
    outputs:
      job: ${{ steps.generate.outputs.job }}
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.target }}

    - id: generate
      uses: sillsdev/codesign/generate-digest@fix/combine-partialy-signed-variables
      with:
        path: ${{ inputs.target }}
        hash: ${{ inputs.hash }}
        url: ${{ inputs.url }}
        public-cert: ${{ secrets.certificate }}

  remotesign:
    needs: digest
    uses: sillsdev/codesign/.github/workflows/sign-digest.yml@fix/combine-partialy-signed-variables
    with:
      digest: ${{ needs.digest.outputs.job }}
   
  finalise:
    needs: remotesign
    runs-on: windows-latest
    steps:
    - uses: sillsdev/codesign/apply-signed-digest@fix/combine-partialy-signed-variables
      with:
        job: ${{ needs.remotesign.outputs.signed-job }}

    - id: timestamp
      uses:  sillsdev/codesign/timestamp@fix/combine-partialy-signed-variables
      with:
        job: ${{ needs.remotesign.outputs.signed-job }}
    
    - id: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.target}}
        path: ${{inputs.target}}
        if-no-files-found: error
        overwrite: true
