name: Sign digest
on:
  workflow_call:
    inputs:
      profile:
        default: "LsDevSectigoEV"
        type: string
      hash:
        default: "sha256"
        type: string
      target:
        required: true
        type: string
      digest:
        required: true
        type: string
    outputs:
      signed-digest:
        description: "Signature for the supplied digest"
        value: ${{ jobs.sign-digest.outputs.digest }}

jobs:
  sign-digest:
    runs-on: [self-hosted, ltops-signing]
    outputs:
      digest: ${{ steps.sign.outputs.digest }}
    steps:
    - id: sign
      run: echo "digest=$(sign-digest ${{inputs.profile}} ${{inputs.hash}} '${{inputs.digest}}')" >> "$GITHUB_OUTPUT"
