name: Sign file
on:
  workflow_call:
    inputs:
      profile:
        default: "LsDevSectigoEV"
        type: string
      hash:
        default: "sha256"
        type: string
      url:
        default: "https://software.sil.org"
        type: string
      target:
        required: true
        type: string
    secrets:
      certificate:
        required: true
env:
  signtool: C:/"Program Files (x86)"/"Windows Kits"/10/bin/10.0.17763.0/x86/signtool.exe
  timestamp_url: http://timestamp.sectigo.com

jobs:
  digest:
    runs-on: windows-latest
    outputs:
      digest: ${{ steps.generate.outputs.digest }}
      intermediates: ${{ steps.generate.outputs.artifact }}
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: ${{inputs.target}}

    - id: generate
      uses: sillsdev/codesign/generate-digest@v1
      with:
        path: ${{ inputs.target }}
        hash: ${{ inputs.hash }}
        url: ${{ inputs.url }}
        public-cert: ${{ secrets.certificate }}

  remotesign:
    needs: digest
    uses: sillsdev/codesign/.github/workflows/sign-digest.yml@v1
    with:
      digest: ${{needs.digest.outputs.digest}}
   
  finalise:
    needs: [digest, remotesign]
    runs-on: windows-latest
    steps:
    - uses: sillsdev/codesign/apply-signed-digest@v1
      with:
        artifact: ${{ needs.digest.outputs.intermediates }}
        path: ${{ inputs.target }}
        signed-digest: ${{ needs.remotesign.outputs.signed-digest }}

    - id: timestamp
      uses:  sillsdev/codesign/timestamp@v1
      with:
        path: ${{inputs.target}}
    
    - id: upload
      uses: actions/upload-artifact@v4
      with:
        name: ${{inputs.target}}
        path: ${{inputs.target}}
        if-no-files-found: error
        overwrite: true
